import XCTest
@testable import EkitapligimCore

/// Locks resolved Turkish copy against the current Android reference screens.
/// Catalog overrides `defaultValue`, so these assert what users actually see.
final class AndroidParityCopyTests: XCTestCase {
    func testBookCommentsCopyMatchesAndroidBookDetailScreen() {
        XCTAssertEqual(L10n.bookCommentsTitleCount(3), "Kullanıcı Yorumları (3)")
        XCTAssertEqual(L10n.bookCommentsYourRating, "Puanınız:")
        XCTAssertEqual(L10n.bookCommentsPlaceholder, "Bu kitap hakkındaki düşüncelerinizi paylaşın...")
        XCTAssertEqual(L10n.bookCommentsSubmit, "Yorum Gönder")
        XCTAssertEqual(L10n.bookCommentsSignedInSubtitle, "Kitap hakkındaki düşüncelerinizi paylaşın.")
        XCTAssertEqual(L10n.bookCommentsGuestSubtitle, "Yorum yazmak için üye olun veya giriş yapın.")
        XCTAssertEqual(L10n.bookCommentsLoginToComment, "Giriş")
    }

    func testBookRequestsCopyMatchesAndroidSocialScreen() {
        XCTAssertEqual(L10n.bookRequestsHeroTitle, "Sosyal & Topluluk")
        XCTAssertEqual(L10n.bookRequestsHeroSubtitle, "Ortak okuma gruplarına katıl,\nkütüphaneye yeni kitap iste!")
        XCTAssertEqual(L10n.bookRequestsListSection, "Kitap İstek Listesi")
        XCTAssertEqual(L10n.bookRequestsCreateDialogTitle, "Yeni Kitap İstemi Yap")
        XCTAssertEqual(L10n.bookRequestsBookTitle, "Kitap Adı")
        XCTAssertEqual(L10n.bookRequestsAuthor, "Yazar")
        XCTAssertEqual(L10n.bookRequestsISBN, "ISBN (Opsiyonel)")
        XCTAssertEqual(L10n.bookRequestsSubmitting, "Gönderiliyor...")
        XCTAssertEqual(L10n.commonSubmit, "Gönder")
        XCTAssertEqual(L10n.bookRequestsEmptyTitle, "Henüz kitap isteği yapılmamış.")
        XCTAssertEqual(L10n.bookRequestsRequestAction, "İstekte Bulun")
        XCTAssertEqual(L10n.bookRequestsGuestCreateHint, "İstek göndermek için önce giriş yapmalısınız.")
        XCTAssertEqual(L10n.bookRequestsAuthorLine(""), "Yazar: Belirtilmemiş")
        XCTAssertEqual(L10n.bookRequestsAuthorLine("Orhan Pamuk"), "Yazar: Orhan Pamuk")
        XCTAssertEqual(L10n.bookRequestsStatus("ACQUIRED"), "Temin Edildi")
        XCTAssertEqual(L10n.bookRequestsStatus("REJECTED"), "Uygun Bulunmadı")
        XCTAssertEqual(L10n.bookRequestsStatus("PENDING"), "Oylanıyor")
        XCTAssertEqual(L10n.bookRequestsVoteCount(7), "7 Oy")
        XCTAssertEqual(L10n.bookRequestsVoteAccessibility, "Upvote")
        XCTAssertEqual(L10n.bookRequestsRequestedBy("Ada"), "İsteyen: Ada")
        XCTAssertEqual(L10n.commonCancel, "İptal")
    }

    func testForumCopyMatchesAndroidThreadScreens() {
        XCTAssertEqual(L10n.forumThreadsEmptyTitle, "Bu forumda henüz konu yok.")
        XCTAssertEqual(L10n.forumThreadsCreateDialogTitle, "Yeni konu aç")
        XCTAssertEqual(L10n.forumThreadsCreateTitlePlaceholder, "Konu başlığı")
        XCTAssertEqual(L10n.forumThreadsCreateMessageSection, "İlk mesaj")
        XCTAssertEqual(L10n.forumThreadsCreateSubmit, "Oluştur")
        XCTAssertEqual(L10n.bookDetailTitle, "Kitap Detayı")
        XCTAssertEqual(L10n.chatSessionPreparingTitle, "Sohbet hesabın hazırlanıyor")
        XCTAssertEqual(L10n.chatSessionPreparingSubtitle, "Oturumun güvenli biçimde doğrulanıyor…")
        XCTAssertEqual(L10n.forumThreadReplyPlaceholder, "Cevabınızı yazın...")
        XCTAssertEqual(L10n.forumThreadSubmitReply, "Cevapla")
        XCTAssertEqual(L10n.forumThreadReportAction, "Raporla")
        XCTAssertEqual(L10n.forumThreadGuestReplyTitle, "Cevap yazmak için kayıt olun")
        XCTAssertEqual(L10n.forumThreadGuestReplyMessage, "Forum sohbetine katılmak için giriş yapın veya ücretsiz hesap oluşturun.")
        XCTAssertEqual(L10n.forumThreadGuestLoginShort, "Giriş")
        XCTAssertEqual(L10n.forumThreadEmptyPosts, "Bu konuda mesaj bulunamadı.")
        XCTAssertEqual(L10n.forumMessageEmpty, "Mesaj içeriği görüntülenemedi.")
        XCTAssertEqual(L10n.forumThreadReplyPermissionHint, "Cevap yetkiniz gönderim sırasında kontrol edilir.")
        XCTAssertEqual(L10n.forumThreadsEmptyDescription, "İlk konuyu açmak için sağ üstteki + düğmesine dokunun.")
        XCTAssertEqual(L10n.forumThreadsCreate, "Konu Aç")
        XCTAssertEqual(L10n.forumThreadsCreateAccessibility, "Yeni konu")
        XCTAssertEqual(L10n.forumThreadsCommunitySubtitle, "Ekitaplığım topluluk forumu")
        XCTAssertEqual(L10n.forumThreadsLoadMore, "Daha fazla konu yükle")
        XCTAssertEqual(L10n.forumThreadPostImage, "Forum görseli")
    }

    func testChatCopyMatchesAndroidChatScreen() {
        XCTAssertEqual(L10n.chatTitle, "Okur Sohbeti")
        XCTAssertEqual(L10n.chatSubtitle, "Kitapları birlikte konuşalım")
        XCTAssertEqual(L10n.chatLiveBadge, "CANLI")
        XCTAssertEqual(L10n.chatComposerPlaceholder, "Okurlarla paylaş…")
        XCTAssertEqual(L10n.chatComposerSend, "Gönder")
        XCTAssertEqual(L10n.chatMessagesEmpty, "Bu odada henüz mesaj yok. İlk mesajı sen yazabilirsin.")
        XCTAssertEqual(L10n.chatRefresh, "Sohbeti yenile")
        XCTAssertEqual(L10n.chatTimeNow, "Şimdi")
        XCTAssertEqual(L10n.chatSendFailed, "Mesaj gönderilemedi. Lütfen tekrar deneyin.")
        XCTAssertEqual(L10n.chatSessionRefresh, "Oturumu yenile")
        XCTAssertEqual(L10n.chatComposerGuestTitle, "Sohbete sen de katıl")
        XCTAssertEqual(L10n.chatComposerGuestSubtitle, "Mesaj yazmak ve okurlarla buluşmak için giriş yap.")
        XCTAssertEqual(L10n.chatComposerSessionTitle, "Mesajlar görünür, oturumun yenilenmeli")
        XCTAssertEqual(L10n.chatComposerSessionSubtitle, "Okumaya devam edebilirsin. Mesaj yazmak için hesabına tekrar bağlan.")
        XCTAssertEqual(L10n.chatComposerReadOnlyTitle, "Bu oda okuma modunda")
        XCTAssertEqual(L10n.chatComposerReadOnlySubtitle, "Duyuruları ve yeni mesajları buradan takip edebilirsin.")
        XCTAssertEqual(L10n.chatComposerNoPermission, "Bu hesap için mesaj gönderme yetkisi bulunmuyor.")
        XCTAssertEqual(L10n.commonLogin, "Giriş yap")
        XCTAssertEqual(L10n.profilePhotoAccessibility("Ada"), "Ada profil resmi")
        XCTAssertEqual(L10n.chatLoadOlder, "Önceki mesajları göster")
        XCTAssertEqual(L10n.commonLoading, "Yükleniyor")
        XCTAssertEqual(L10n.chatRoleAdmin, "YÖNETİCİ")
        XCTAssertEqual(L10n.chatRoleModerator, "MODERATÖR")
        XCTAssertEqual(L10n.chatEdited, " · düzenlendi")
    }

    func testAgendaAndLibraryCopyMatchesAndroidScreens() {
        XCTAssertEqual(L10n.agendaHeroEyebrow, "OKUDUĞUNU PAYLAŞ")
        XCTAssertEqual(L10n.agendaComposerPlaceholder, "Ne paylaşmak istiyorsun?")
        XCTAssertEqual(L10n.agendaCommentPlaceholder, "Kitap hakkında ne düşünüyorsun?")
        XCTAssertEqual(L10n.agendaTypeNote, "Not")
        XCTAssertEqual(L10n.agendaTypeBook, "Kitap")
        XCTAssertEqual(L10n.agendaTypeQuotation, "Alıntı")
        XCTAssertEqual(L10n.agendaTypeReview, "İnceleme")
        XCTAssertEqual(L10n.agendaTypeProgressCompose, "İlerleme")
        XCTAssertEqual(L10n.agendaTypeProgress, "Okuma")
        XCTAssertEqual(L10n.agendaTypeQuote, "Alıntılandı")
        XCTAssertEqual(L10n.agendaTypeStandard, "Paylaşım")
        XCTAssertEqual(L10n.agendaQuotedFrom("Ada"), "Ada adlı üyeden alıntı")
        XCTAssertEqual(L10n.agendaComposerTitle, "Yeni paylaşım")
        XCTAssertEqual(L10n.agendaComposerSubtitle, "Okuma deneyimini toplulukla paylaş.")
        XCTAssertEqual(L10n.agendaComposerSelectBook, "Kitap seç")
        XCTAssertEqual(L10n.agendaComposerRating(5), "Puan: 5/5")
        XCTAssertEqual(L10n.agendaComposerSearchBook, "Kitap veya yazar ara")
        XCTAssertEqual(L10n.agendaComposerQuotePlaceholder, "Alıntıyı yaz...")
        XCTAssertEqual(L10n.agendaComposerEmptyMessage, "Paylaşım metni boş olamaz.")
        XCTAssertEqual(L10n.agendaComposerBookRequired, "Bu paylaşım türü için kitap seçmelisin.")
        XCTAssertEqual(L10n.agendaComposerProgressInvalid, "İlerleme sayfası toplam sayfadan büyük olamaz.")
        XCTAssertEqual(L10n.agendaComposerFailed, "Paylaşım gönderilemedi.")
        XCTAssertEqual(L10n.agendaComposerPageNumber, "Sayfa numarası")
        XCTAssertEqual(L10n.agendaComposerProgressCurrent, "Şu an")
        XCTAssertEqual(L10n.agendaComposerProgressTotal, "Toplam")
        XCTAssertEqual(L10n.agendaOpenBook, "Kitabı aç")
        XCTAssertEqual(L10n.agendaComments, "Yorumlar")
        XCTAssertEqual(L10n.agendaRepost, "Yeniden paylaş")
        XCTAssertEqual(L10n.agendaBookmark, "Kaydet")
        XCTAssertEqual(L10n.profileVerifiedAccessibility, "Doğrulanmış")
        XCTAssertEqual(L10n.agendaTabPersonal, "Sana Özel")
        XCTAssertEqual(L10n.agendaTabLocked, "Giriş gerekli")
        XCTAssertEqual(L10n.agendaTabPersonalSubtitle, "Senin için")
        XCTAssertEqual(L10n.agendaTabFollowing, "Takip Ettiklerin")
        XCTAssertEqual(L10n.agendaTabFollowingSubtitle, "Üyeler ve raflar")
        XCTAssertEqual(L10n.agendaTabAgenda, "Kitap Gündemi")
        XCTAssertEqual(L10n.agendaTabAgendaSubtitle, "Toplulukta bugün")
        XCTAssertEqual(L10n.commonClose, "Kapat")
        XCTAssertEqual(L10n.agendaPinned, "Sabitlendi")
        XCTAssertEqual(L10n.agendaFeatured, "Öne çıkan")
        XCTAssertEqual(L10n.agendaFollow, "Takip et")
        XCTAssertEqual(L10n.agendaPostOptions, "Paylaşım seçenekleri")
        XCTAssertEqual(L10n.agendaRefresh, "Gündemi yenile")
        XCTAssertEqual(L10n.agendaCommentOptions, "Yorum seçenekleri")
        XCTAssertEqual(L10n.timeJustNow, "Az önce")
        XCTAssertEqual(L10n.timeMinutesAgo(5), "5 dk önce")
        XCTAssertEqual(L10n.timeHoursAgo(2), "2 sa önce")
        XCTAssertEqual(L10n.timeDaysAgo(3), "3 gün önce")
        XCTAssertEqual(L10n.chatRoomsFailed, "Sohbet odaları yüklenemedi.")
        XCTAssertEqual(L10n.chatRoomsLoading, "Sohbet odaları hazırlanıyor…")
        XCTAssertEqual(L10n.chatRoomsLoadingSubtitle, "Canlı topluluk bağlantısı kuruluyor")
        XCTAssertEqual(L10n.chatMessagesLoading, "Mesajlar yükleniyor…")
        XCTAssertEqual(L10n.chatRoomsEmpty, "Şu anda katılabileceğiniz bir sohbet odası yok.")
        XCTAssertEqual(L10n.chatHeroTitle, "Canlı okur topluluğu")
        XCTAssertEqual(L10n.chatHeroSubtitle, "Kitapları konuş, yeni keşiflere birlikte ulaş.")
        XCTAssertEqual(L10n.chatHeroLiveUpdate, "Mesajlar anlık güncellenir")
        XCTAssertEqual(L10n.chatStatusMember, "Üye olarak bağlısın")
        XCTAssertEqual(L10n.chatStatusSecureRead, "Güvenli okuma modu")
        XCTAssertEqual(L10n.chatStatusGuest, "Misafir olarak izliyorsun")
        XCTAssertEqual(L10n.chatWelcomeReady, "Sohbete katılmaya hazırsın")
        XCTAssertEqual(L10n.chatWelcomeSecure, "Mesajlar güvenli okuma modunda gösteriliyor")
        XCTAssertEqual(L10n.chatWelcomeGuest, "Misafir olarak canlı mesajları takip ediyorsun")
        XCTAssertEqual(L10n.chatWelcomeRules, "Topluluk kurallarına saygı göstererek kitapları birlikte konuşalım.")
        XCTAssertEqual(L10n.chatMessagesFailed, "Sohbet mesajları yüklenemedi.")
        XCTAssertEqual(L10n.agendaFollowing, "Takipte")
        XCTAssertEqual(L10n.libraryAuthorMissing, "Yazar bilgisi yok")
        XCTAssertEqual(L10n.agendaComposerPromptTitle, "Yeni bir paylaşım oluştur")
        XCTAssertEqual(L10n.agendaComposerPromptSubtitle, "Ne okuyorsun ya da ne paylaşmak istiyorsun?")
        XCTAssertEqual(L10n.agendaComposerGuestTitle, "Topluluğa katıl")
        XCTAssertEqual(L10n.agendaComposerGuestSubtitle, "Paylaşmak ve etkileşim kurmak için giriş yap.")
        XCTAssertEqual(L10n.agendaCommentComposerTitle, "Yorumunu paylaş")
        XCTAssertEqual(L10n.agendaCommentGuestTitle, "Yorum yapmak için giriş yap")
        XCTAssertEqual(L10n.libraryTabReading, "Okuyorum")
        XCTAssertEqual(L10n.libraryTabWantToRead, "Daha sonra oku")
        XCTAssertEqual(L10n.libraryTabFinished, "Okudum")
        XCTAssertEqual(L10n.libraryTabFavorites, "Favoriler")
        XCTAssertEqual(L10n.libraryTabDownloads, "İndirme geçmişi")
        XCTAssertEqual(L10n.libraryEmptyTitle, "Bu rafta henüz kitap yok.")
        XCTAssertEqual(L10n.libraryEmptyDescription, "Kitap eklediğinde burada görünecek.")
        XCTAssertEqual(L10n.libraryHeaderTitle, "Kişisel Kitaplığım")
        XCTAssertEqual(L10n.libraryOpenBookDetail, "Kitap detayını aç")
        XCTAssertEqual(L10n.libraryCoverAccessibility("Sinekli Bakkal"), "Sinekli Bakkal kapağı")
        XCTAssertEqual(L10n.libraryHeaderSubtitle, "Okuma yolculuğunu raflarına göre yönet.")
        XCTAssertEqual(L10n.librarySelectedShelfLabel, "Seçili raf")
        XCTAssertEqual(L10n.librarySelectedShelfBooks(3), "3 kitap bu rafta")
        XCTAssertEqual(L10n.libraryBookCountLabel, "kitap")
        XCTAssertEqual(L10n.libraryShelfAdd, "Rafa Ekle")
        XCTAssertEqual(L10n.libraryShelfLaterShort, "Daha sonra")
        XCTAssertEqual(L10n.libraryShelfLater, "Daha sonra oku")
        XCTAssertEqual(L10n.libraryShelfReading, "Okuyorum")
        XCTAssertEqual(L10n.libraryShelfFinished, "Okudum")
        XCTAssertEqual(L10n.libraryShelfRemove, "Raftan Kaldır")
        XCTAssertEqual(L10n.bookDetailRead, "Hemen Oku")
        XCTAssertEqual(L10n.bookDetailOfflineDownload, "İndir")
        XCTAssertEqual(L10n.bookDetailInfoYear, "Yayın Yılı")
        XCTAssertEqual(L10n.bookDetailInfoTitle, "Kitap Künyesi")
        XCTAssertEqual(L10n.bookDetailSimilarBooks, "Benzer Kitaplar")
        XCTAssertEqual(L10n.bookDetailInfoFormat, "Format")
        XCTAssertEqual(L10n.bookDetailUnknownFormat, "PDF / EPUB")
        XCTAssertEqual(L10n.bookDetailSynopsisSectionTitle, "Özet / Açıklama")
        XCTAssertEqual(L10n.bookDetailAddToFavorites, "Favorilerime ekle")
        XCTAssertEqual(L10n.bookDetailSynopsisTitle, "Kitap Özeti")
        XCTAssertEqual(L10n.bookDetailSynopsisSubtitle, "Açıklama içeriği")
        XCTAssertEqual(L10n.bookDetailMissingDescription, "Bu kitap için özet henüz eklenmemiş.")
        XCTAssertEqual(L10n.bookDetailSynopsisReadMore, "Devamını oku")
        XCTAssertEqual(L10n.bookDetailSynopsisShowLess, "Daha az göster")
        XCTAssertEqual(L10n.bookDetailUnspecified, "Belirtilmemiş")
        XCTAssertEqual(L10n.bookDetailDownloadCount(12), "12 indirme")
        XCTAssertEqual(L10n.forumThreadDetailMeta(4), "4 mesaj · Ekitaplığım Forum")
        XCTAssertEqual(L10n.homeSeeAll, "Tümünü gör")
        XCTAssertEqual(L10n.bookDetailIssueTitle, "Sorun mu var?")
        XCTAssertEqual(L10n.bookDetailIssueSubtitle, "Kitap kaydıyla ilgili hızlı bildirim gönderin.")
        XCTAssertEqual(L10n.bookDetailIssueBrokenLink, "Kırık link")
        XCTAssertEqual(L10n.bookDetailIssueMissingCover, "Eksik kapak")
        XCTAssertEqual(L10n.bookDetailIssueCopyright, "Telif")
        XCTAssertEqual(L10n.bookDetailIssueLoginRequired, "Bildirimde bulunmak için giriş yapmalısınız.")
        XCTAssertEqual(L10n.bookDetailIssueCopyrightLoginRequired, "Telif bildirimi için giriş yapmalısınız.")
        XCTAssertEqual(L10n.bookDetailIssueSubmitted("Kırık link"), "Kırık link bildiriminiz alındı.")
        XCTAssertEqual(L10n.bookDetailIssueSubmitFailed, "Bildirim gönderilemedi. Lütfen tekrar deneyin.")
        XCTAssertEqual(L10n.libraryMetaFinished, "Tamamlandı")
        XCTAssertEqual(L10n.libraryMetaWantToRead, "Daha sonra oku")
        XCTAssertEqual(L10n.libraryMetaFavorite, "Favorilerde")
        XCTAssertEqual(L10n.libraryMetaDownloaded, "İndirildi")
        XCTAssertEqual(L10n.libraryDownloadOfflineReady, "Cihazda çevrimdışı okumaya hazır")
        XCTAssertEqual(L10n.libraryDownloadServerHistory, "Daha önce indirildi")
        XCTAssertEqual(L10n.libraryMetaContinue, "Devam et")
        XCTAssertEqual(L10n.libraryMetaLastPage(12), "Kaldığın yer: 12. sayfa")
        XCTAssertEqual(L10n.chatReconnectTitle, "Topluluğa yeniden bağlanalım")
        XCTAssertEqual(L10n.chatReconnect, "Tekrar bağlan")
        XCTAssertEqual(L10n.bookDetailIssueBrokenLinkReportTitle, "Kırık link bildir")
        XCTAssertEqual(L10n.bookDetailIssueMissingCoverReportTitle, "Eksik kapak bildir")
        XCTAssertEqual(L10n.bookDetailIssueCopyrightReportTitle, "Telif bildirimi gönder")
        XCTAssertEqual(L10n.forumThreadReportPost, "Mesajı raporla")
        XCTAssertEqual(L10n.forumThreadReportSubmit, "Raporla")
        XCTAssertEqual(L10n.forumThreadReportPlaceholder, "Kısa açıklama yazın...")
        XCTAssertEqual(L10n.forumThreadReportDescription, "Bu forum mesajında spam, hakaret, telif ihlali veya uygunsuz içerik olduğunu düşünüyorsanız yönetime bildirin.")
        XCTAssertEqual(L10n.commonDismiss, "Vazgeç")
        XCTAssertEqual(L10n.commonSubmit, "Gönder")
        XCTAssertEqual(L10n.agendaPostEditTitle, "Paylaşımı düzenle")
        XCTAssertEqual(L10n.agendaPostLabel, "Paylaşım")
        XCTAssertEqual(L10n.agendaPostVisibilityTitle, "Kimler görebilir?")
        XCTAssertEqual(L10n.agendaVisibilityPublic, "Herkes")
        XCTAssertEqual(L10n.agendaVisibilityMembers, "Üyeler")
        XCTAssertEqual(L10n.agendaVisibilityFollowers, "Takipçiler")
        XCTAssertEqual(L10n.agendaVisibilityPrivate, "Yalnızca ben")
        XCTAssertEqual(L10n.agendaCommentEditTitle, "Yorumu düzenle")
        XCTAssertEqual(L10n.commonSave, "Kaydet")
        XCTAssertEqual(L10n.commonSaving, "Kaydediliyor…")
        XCTAssertEqual(L10n.commonShare, "Paylaş")
        XCTAssertEqual(L10n.commonBack, "Geri")
        XCTAssertEqual(L10n.commonRetryAgain, "Yeniden dene")
        XCTAssertEqual(L10n.commonLoadMoreItems, "Daha fazla göster")
        XCTAssertEqual(L10n.agendaCommentsEmptyTitle, "Henüz yorum yok")
        XCTAssertEqual(L10n.agendaCommentsEmptySubtitle, "İlk yorumu sen yazabilirsin.")
        XCTAssertEqual(L10n.agendaFeedErrorTitle, "Akış yüklenemedi")
        XCTAssertEqual(L10n.agendaFeedEmptyTitle, "Bu rafta henüz paylaşım yok")
        XCTAssertEqual(L10n.agendaFeedEmptySubtitle, "İlk kitap notunu sen paylaşabilirsin.")
    }

    func testProfileGuestAndLoginCopyMatchesAndroid() {
        XCTAssertEqual(L10n.profileScreenTitle, "Profilim")
        XCTAssertEqual(L10n.profileGuestTitle, "Kütüphanene hoş geldin")
        XCTAssertEqual(
            L10n.profileGuestSubtitle,
            "Raflarını, favorilerini, yorumlarını ve okuma geçmişini tek dokunuşla yanında taşı."
        )
        XCTAssertEqual(L10n.profileGuestManageSubtitle, "Hesabını yönet, kütüphaneni senkronize et.")
        XCTAssertEqual(L10n.profileGuestShelfSync, "Raf senkronu")
        XCTAssertEqual(L10n.profileGuestShelfSyncSubtitle, "Kitapların hep hazır,\nher cihazında seninle.")
        XCTAssertEqual(L10n.profileGuestLimits, "Limit takibi")
        XCTAssertEqual(L10n.profileGuestLimitsSubtitle, "Okuma limitlerini takip et,\nhaklarını kontrol altında tut.")
        XCTAssertEqual(L10n.profileGuestFavorites, "Favoriler")
        XCTAssertEqual(L10n.profileGuestFavoritesSubtitle, "Seçtiklerini kaydet,\nkolayca yeniden ulaş.")
        XCTAssertEqual(L10n.profileGuestSecure, "Güvenli erişim")
        XCTAssertEqual(L10n.profileGuestSecureSubtitle, "Hesabın güvende,\nverilerin koruma altında.")
        XCTAssertEqual(L10n.profileGuestFooter, "Güvenli bağlantı ile verileriniz korunur.")
        XCTAssertEqual(L10n.commonLogin, "Giriş yap")
        XCTAssertEqual(L10n.loginModeRegister, "Kayıt Ol")
        XCTAssertEqual(L10n.loginCommunityTagline, "Ekitaplığım Kütüphane Topluluğu")
        XCTAssertEqual(L10n.loginSignalShelf, "Raf senkronu")
        XCTAssertEqual(L10n.loginSignalAPI, "Güvenli API")
        XCTAssertEqual(L10n.loginSignalPremium, "Premium erişim")
        XCTAssertEqual(L10n.loginBadgeLogin, "Üye girişi")
        XCTAssertEqual(L10n.loginBadgeRegister, "Yeni üyelik")
        XCTAssertEqual(L10n.loginBadgeReset, "Hesap kurtarma")
        XCTAssertEqual(L10n.loginHeadingLogin, "Giriş Yap")
        XCTAssertEqual(L10n.loginRegisterTitle, "Yeni Hesap Oluştur")
        XCTAssertEqual(L10n.loginResetTitle, "Şifre Sıfırlama")
        XCTAssertEqual(
            L10n.loginSubtitleLogin,
            "Kitaplığın, favorilerin ve günlük limitlerin tek hesapta senkronize olsun."
        )
        XCTAssertEqual(
            L10n.loginSubtitleRegister,
            "Kitap raflarını ve okuma limitlerini hesabınla güvenle eşleştir."
        )
        XCTAssertEqual(L10n.loginSubtitleReset, "E-posta adresine şifre sıfırlama bağlantısı gönderelim.")
        XCTAssertEqual(L10n.loginUsernamePlaceholder, "Kullanıcı Adı veya E-posta")
        XCTAssertEqual(L10n.loginEmailPlaceholder, "E-posta Adresi")
        XCTAssertEqual(L10n.loginPasswordPlaceholder, "Şifre")
        XCTAssertEqual(L10n.loginPasswordConfirmation, "Şifre Tekrar")
        XCTAssertEqual(L10n.loginForgotPassword, "Şifremi Unuttum")
        XCTAssertEqual(L10n.loginSubmit, "Giriş Yap")
        XCTAssertEqual(L10n.loginRegisterSubmit, "Kayıt Ol")
        XCTAssertEqual(L10n.loginResetSubmit, "Sıfırlama Bağlantısı Gönder")
        XCTAssertEqual(L10n.loginSwitchToRegister, "Henüz hesabınız yok mu? Kayıt olun")
        XCTAssertEqual(L10n.loginSwitchToLogin, "Zaten hesabınız var mı? Giriş yapın")
        XCTAssertEqual(L10n.loginBackToLogin, "Giriş Ekranına Dön")
        XCTAssertEqual(
            L10n.loginAcceptLegalBody,
            "Hesap oluşturarak E-Kitaplığım Kullanım Şartları ve Gizlilik Politikası'nı kabul ediyorum."
        )
    }

    func testConversationsCopy() {
        XCTAssertEqual(L10n.conversationsTitle, "Mesajlar")
        XCTAssertEqual(L10n.conversationsYou, "Siz")
        XCTAssertEqual(L10n.conversationsStarred, "Yıldızlı")
        XCTAssertEqual(L10n.conversationsReplyCount(3), "3 yanıt")
        XCTAssertEqual(L10n.conversationsReplyPlaceholder, "Yanıt yazın")
        XCTAssertEqual(L10n.conversationsNew, "Yeni mesaj")
        XCTAssertEqual(L10n.conversationsSubject, "Konu")
    }

    func testCatalogCopyShowsRealTotalsNotPageSize() {
        XCTAssertEqual(L10n.catalogHeroTitle, "Kataloğu Keşfet")
        XCTAssertEqual(L10n.catalogEyebrow, "KATALOG")
        XCTAssertEqual(L10n.catalogHeroBooksCaption, "kitap")
        XCTAssertEqual(L10n.catalogHeroBookCount("14.409"), "14.409 kitap")
        XCTAssertEqual(
            L10n.catalogHeroSubtitle(category: "Tüm kategoriler", page: 1, lastPage: 734),
            "Tüm kategoriler · Sayfa 1 / 734"
        )
        XCTAssertFalse(
            L10n.catalogHeroSubtitle(category: "Tüm kategoriler", page: 1, lastPage: 734)
                .contains("20 kitap")
        )
        XCTAssertEqual(L10n.catalogStatTotal, "Toplam")
        XCTAssertEqual(L10n.catalogStatLoaded, "Yüklenen")
        XCTAssertEqual(L10n.catalogStatCatalogPage, "Katalog sayfası")
        XCTAssertEqual(L10n.catalogPagePosition(1, 734), "1 / 734")
        XCTAssertEqual(L10n.catalogCategoryChip("Roman", countLabel: "3.251"), "Roman  3.251")
        XCTAssertEqual(L10n.catalogBookPageCount(240), "240 syf")
    }
}
