import Foundation

public enum L10n {
    public static let bookDetailTitle = localized("book.detail.title", defaultValue: "Kitap Detayı")
    public static let bookDetailLoading = localized("book.detail.loading", defaultValue: "Kitap yükleniyor")
    public static let bookDetailOpenFailed = localized("book.detail.openFailed", defaultValue: "Kitap açılamadı")
    public static let bookDetailMissingDescription = localized("book.detail.missingDescription", defaultValue: "Açıklama bulunmuyor.")
    public static let bookDetailRead = localized("book.detail.read", defaultValue: "Oku")
    public static let bookDetailCheckReading = localized("book.detail.checkReading", defaultValue: "Okuma durumunu kontrol et")
    public static let bookDetailOfflineDownload = localized("book.detail.offlineDownload", defaultValue: "Çevrimdışı indir")
    public static let bookDetailReportIssue = localized("book.detail.reportIssue", defaultValue: "Sorun bildir")
    public static let bookDetailLoadFailed = localized("book.detail.loadFailed", defaultValue: "Kitap bilgileri alınamadı.")
    public static let bookDetailSimilarBooks = localized("book.detail.similarBooks", defaultValue: "Benzer Kitaplar")
    public static let bookDetailInvalidId = localized("book.detail.invalidId", defaultValue: "Kitap kimliği geçersiz.")
    public static let bookDetailSecureDownloadMissing = localized("book.detail.secureDownloadMissing", defaultValue: "Güvenli indirme bağlantısı alınamadı.")
    public static let bookDetailDownloadReady = localized("book.detail.downloadReady", defaultValue: "Kitap çevrimdışı okuma için indirildi.")
    public static let bookDetailDownloadStarted = localized("book.detail.downloadStarted", defaultValue: "İndirme başlatıldı.")
    public static let bookCommentsTitle = localized("bookComments.title", defaultValue: "Kullanıcı Yorumları")
    public static let bookCommentsPlaceholder = localized("bookComments.placeholder", defaultValue: "Bu kitap hakkındaki düşüncelerinizi paylaşın")
    public static let bookCommentsSubmit = localized("bookComments.submit", defaultValue: "Yorum gönder")
    public static let bookCommentsEmpty = localized("bookComments.empty", defaultValue: "Henüz yorum yapılmamış.")
    public static let bookCommentsLoadFailed = localized("bookComments.loadFailed", defaultValue: "Yorumlar yüklenemedi.")
    public static let bookCommentsSubmitFailed = localized("bookComments.submitFailed", defaultValue: "Yorum gönderilemedi.")
    public static let bookCommentsReport = localized("bookComments.report", defaultValue: "Yorumu bildir")
    public static let bookCommentsLoginToComment = localized("bookComments.loginToComment", defaultValue: "Yorum yapmak için giriş yap")
    public static let bookCommentsLoginRequiredTitle = localized("bookComments.loginRequiredTitle", defaultValue: "Giriş gerekli")
    public static let bookCommentsLoginRequiredMessage = localized("bookComments.loginRequiredMessage", defaultValue: "Yorum yazmak veya bildirmek için giriş yapın.")

    public static func bookCommentsRating(_ rating: Int) -> String {
        String(format: localized("bookComments.rating", defaultValue: "%d yıldız"), rating)
    }
    public static let directoryAuthorsTitle = localized("directory.authors.title", defaultValue: "Yazarlar")
    public static let directoryPublishersTitle = localized("directory.publishers.title", defaultValue: "Yayınevleri")
    public static let directoryLoading = localized("directory.loading", defaultValue: "Dizin yükleniyor")
    public static let directoryUnavailableTitle = localized("directory.unavailableTitle", defaultValue: "Dizin alınamadı")
    public static let directoryEmptyTitle = localized("directory.emptyTitle", defaultValue: "Sonuç bulunamadı")
    public static let directoryEmptyDescription = localized("directory.emptyDescription", defaultValue: "Aramanızı değiştirip yeniden deneyin.")
    public static let directorySearchPrompt = localized("directory.searchPrompt", defaultValue: "Ara")
    public static let directoryLoadFailed = localized("directory.loadFailed", defaultValue: "Yazar ve yayınevi bilgileri alınamadı.")
    public static let commonLoadMore = localized("common.loadMore", defaultValue: "Daha fazla yükle")

    public static func directoryBookCount(_ count: Int) -> String {
        String(format: localized("directory.bookCount", defaultValue: "%d kitap"), count)
    }
    public static let downloadSecureConnectionRequired = localized("download.error.secureConnection", defaultValue: "Güvenli indirme bağlantısı gerekli.")
    public static let downloadServerRejected = localized("download.error.serverRejected", defaultValue: "Dosya indirilemedi.")
    public static let downloadValidationFailed = localized("download.error.validationFailed", defaultValue: "Dosya güvenli biçimde doğrulanamadı.")
    public static let downloadRemovalFailed = localized("download.error.removalFailed", defaultValue: "İndirme silinemedi.")

    public static let readerPreparing = localized("reader.preparing", defaultValue: "Okuma bağlantısı hazırlanıyor")
    public static let readerUnavailable = localized("reader.unavailable", defaultValue: "Okuyucu hazır değil")
    public static let readerSecureLinkMissing = localized("reader.secureLinkMissing", defaultValue: "Güvenli geçici okuma bağlantısı alınamadı.")
    public static let readerInvalidBookId = localized("reader.invalidBookId", defaultValue: "Kitap kimliği geçersiz.")
    public static let readerAtsLinkMissing = localized("reader.atsLinkMissing", defaultValue: "App Store uyumlu güvenli okuma bağlantısı alınamadı.")
    public static let readerSessionFailed = localized("reader.sessionFailed", defaultValue: "Okuma oturumu başlatılamadı.")
    public static let readerUnsupportedFormat = localized("reader.unsupportedFormat", defaultValue: "Bu kitap biçimi desteklenmiyor.")
    public static let readerEPUBFormat = localized("reader.epub.format", defaultValue: "EPUB")
    public static let readerEPUBPreparing = localized("reader.epub.preparing", defaultValue: "EPUB hazırlanıyor")
    public static let readerEPUBUnavailable = localized("reader.epub.unavailable", defaultValue: "EPUB açılamadı")
    public static let readerEPUBOpenFailed = localized("reader.epub.openFailed", defaultValue: "EPUB dosyası güvenli biçimde indirilemedi veya açılamadı.")
    public static let readerAddBookmark = localized("reader.addBookmark", defaultValue: "Bu sayfaya yer imi ekle")
    public static let readerRemoveBookmark = localized("reader.removeBookmark", defaultValue: "Bu sayfadaki yer imini kaldır")
    public static let readerBookmarks = localized("reader.bookmarks", defaultValue: "Yer İmleri")
    public static let readerBookmarksEmpty = localized("reader.bookmarks.empty", defaultValue: "Yer imi yok")
    public static let readerBookmarksEmptyDescription = localized("reader.bookmarks.emptyDescription", defaultValue: "Kaydetmek istediğiniz sayfada yer imi düğmesine dokunun.")

    public static func readerPage(_ current: Int, _ total: Int) -> String {
        String(format: localized("reader.page", defaultValue: "Sayfa %d / %d"), current, total)
    }

    public static func readerPageNumber(_ page: Int) -> String {
        String(format: localized("reader.pageNumber", defaultValue: "Sayfa %d"), page)
    }

    public static let deleteAccountTitle = localized("account.delete.title", defaultValue: "Hesabı Sil")
    public static let deleteAccountWarning = localized("account.delete.warning", defaultValue: "Bu işlem tüm hesabınızın silinmesi sürecini başlatır. Talep genellikle 30 gün içinde tamamlanır ve sonuç kayıtlı e-posta adresinize bildirilir. Profil, kitaplık ve kullanıcı içerikleri silinir veya yasal zorunluluk varsa anonimleştirilir. Apple aboneliğiniz varsa ayrıca App Store aboneliklerinizi yönetin.")
    public static let deleteAccountConfirmationPrompt = localized("account.delete.confirmationPrompt", defaultValue: "Devam etmek için SIL yazın.")
    public static let deleteAccountConfirmationPlaceholder = localized("account.delete.confirmationPlaceholder", defaultValue: "SIL")
    public static let deleteAccountPasswordPlaceholder = localized("account.delete.passwordPlaceholder", defaultValue: "Mevcut şifre (varsa)")
    public static let deleteAccountReasonLabel = localized("account.delete.reasonLabel", defaultValue: "Silme nedeni")
    public static let deleteAccountSubmit = localized("account.delete.submit", defaultValue: "Silme talebi gönder")
    public static let deleteAccountSubmitted = localized("account.delete.submitted", defaultValue: "Hesap silme talebiniz alındı. İşlem genellikle 30 gün içinde tamamlanır ve e-postayla bildirilir.")
    public static let deleteAccountSubmitFailed = localized("account.delete.submitFailed", defaultValue: "Hesap silme talebi gönderilemedi.")

    public static let accountSecurityTitle = localized("account.security.title", defaultValue: "Giriş ve Güvenlik")
    public static let accountSecurityEmailSection = localized("account.security.email.section", defaultValue: "E-posta")
    public static let accountSecurityCurrentEmail = localized("account.security.email.current", defaultValue: "Mevcut e-posta")
    public static let accountSecurityNewEmail = localized("account.security.email.new", defaultValue: "Yeni e-posta")
    public static let accountSecurityCurrentPassword = localized("account.security.currentPassword", defaultValue: "Mevcut şifre")
    public static let accountSecurityUpdateEmail = localized("account.security.email.update", defaultValue: "E-postayı güncelle")
    public static let accountSecurityEmailFooter = localized("account.security.email.footer", defaultValue: "Güvenlik için mevcut şifreniz yeniden doğrulanır. Yeni adres için e-posta onayı gerekebilir.")
    public static let accountSecurityEmailUpdated = localized("account.security.email.updated", defaultValue: "E-posta adresiniz güncellendi.")
    public static let accountSecurityEmailConfirmation = localized("account.security.email.confirmation", defaultValue: "Yeni adresinize gönderilen doğrulama bağlantısını açın.")
    public static let accountSecurityEmailFailed = localized("account.security.email.failed", defaultValue: "E-posta güncellenemedi. Mevcut şifrenizi ve adresi kontrol edin.")
    public static let accountSecurityPasswordSection = localized("account.security.password.section", defaultValue: "Şifre")
    public static let accountSecurityNewPassword = localized("account.security.password.new", defaultValue: "Yeni şifre")
    public static let accountSecurityConfirmPassword = localized("account.security.password.confirm", defaultValue: "Yeni şifre tekrar")
    public static let accountSecurityUpdatePassword = localized("account.security.password.update", defaultValue: "Şifreyi güncelle")
    public static let accountSecurityPasswordFooter = localized("account.security.password.footer", defaultValue: "Şifre değişince diğer mobil oturumlar kapatılır ve bu cihaz için güvenli oturum yenilenir.")
    public static let accountSecurityPasswordUpdated = localized("account.security.password.updated", defaultValue: "Şifreniz ve bu cihazdaki güvenli oturum yenilendi.")
    public static let accountSecurityPasswordFailed = localized("account.security.password.failed", defaultValue: "Şifre güncellenemedi. Mevcut şifrenizi ve yeni şifre kurallarını kontrol edin.")
    public static let accountSecuritySaving = localized("account.security.saving", defaultValue: "Güncelleniyor")

    public static let privacyTitle = localized("privacy.title", defaultValue: "Gizlilik")
    public static let privacyAnalyticsOptIn = localized("privacy.analyticsOptIn", defaultValue: "Kullanım analitiğine izin ver")
    public static let privacyNotificationPreviews = localized("privacy.notificationPreviews", defaultValue: "Bildirim önizlemelerini göster")
    public static let privacyTrackingNotice = localized("privacy.trackingNotice", defaultValue: "Bu uygulama reklam takibi yapacak şekilde tasarlanmamıştır. Analitik etkinleştirilirse App Store gizlilik etiketleri buna göre güncellenmelidir.")
    public static let privacyDataSection = localized("privacy.dataSection", defaultValue: "Veri")
    public static let privacyDataNotice = localized("privacy.dataNotice", defaultValue: "Okuma ilerlemesi, kitaplık, yorumlar ve hesap bilgileri Ekitaplığım hesabınızla ilişkilidir. Hesap silme talebi Hesap bölümünden başlatılır.")
    public static let privacySummarySection = localized("privacy.summarySection", defaultValue: "Gizlilik Özeti")
    public static let privacyTrackingLabel = localized("privacy.trackingLabel", defaultValue: "Uygulamalar arası takip")
    public static let privacyAnalyticsLabel = localized("privacy.analyticsLabel", defaultValue: "Üçüncü taraf analitik")
    public static let privacyAdvertisingLabel = localized("privacy.advertisingLabel", defaultValue: "Reklam SDK'sı")
    public static let privacyNotUsed = localized("privacy.notUsed", defaultValue: "Kullanılmıyor")
    public static let privacyOfflineNotice = localized("privacy.offlineNotice", defaultValue: "İndirilen kitaplar yalnızca uygulama alanında tutulur, cihaz yedeğine eklenmez ve siz kaldırana kadar saklanır.")

    public static let reportTitle = localized("report.title", defaultValue: "İçerik bildir")
    public static let reportReason = localized("report.reason", defaultValue: "Neden")
    public static let reportObjectionable = localized("report.reason.objectionable", defaultValue: "Uygunsuz içerik")
    public static let reportCopyright = localized("report.reason.copyright", defaultValue: "Telif hakkı")
    public static let reportBrokenFile = localized("report.reason.brokenFile", defaultValue: "Bozuk dosya")
    public static let reportOther = localized("report.reason.other", defaultValue: "Diğer")
    public static let reportMessageLabel = localized("report.messageLabel", defaultValue: "Rapor açıklaması")
    public static let reportFooter = localized("report.footer", defaultValue: "Raporlar moderasyon ekibine gönderilir. Kötüye kullanım bildirimleri güvenlik amacıyla incelenir.")
    public static let reportSubmit = localized("report.submit", defaultValue: "Raporu gönder")
    public static let commonClose = localized("common.close", defaultValue: "Kapat")
    public static let commonCancel = localized("common.cancel", defaultValue: "İptal")
    public static let commonSubmit = localized("common.submit", defaultValue: "Gönder")
    public static let commonRetry = localized("common.retry", defaultValue: "Tekrar dene")
    public static let reportSubmitted = localized("report.submitted", defaultValue: "Raporunuz alındı.")
    public static let reportSubmitFailed = localized("report.submitFailed", defaultValue: "Rapor gönderilemedi.")

    public static let bookRequestsTitle = localized("bookRequests.title", defaultValue: "Kitap İstekleri")
    public static let bookRequestsLoading = localized("bookRequests.loading", defaultValue: "Kitap istekleri yükleniyor")
    public static let bookRequestsUnavailableTitle = localized("bookRequests.unavailableTitle", defaultValue: "İstekler alınamadı")
    public static let bookRequestsEmptyTitle = localized("bookRequests.emptyTitle", defaultValue: "Henüz kitap isteği yok")
    public static let bookRequestsEmptyDescription = localized("bookRequests.emptyDescription", defaultValue: "Aradığınız kitabı ilk siz isteyebilirsiniz.")
    public static let bookRequestsCreate = localized("bookRequests.create", defaultValue: "Yeni kitap isteği")
    public static let bookRequestsBookTitle = localized("bookRequests.bookTitle", defaultValue: "Kitap adı")
    public static let bookRequestsAuthor = localized("bookRequests.author", defaultValue: "Yazar")
    public static let bookRequestsAuthorMissing = localized("bookRequests.authorMissing", defaultValue: "Yazar belirtilmemiş")
    public static let bookRequestsISBN = localized("bookRequests.isbn", defaultValue: "ISBN (isteğe bağlı)")
    public static let bookRequestsSubmitting = localized("bookRequests.submitting", defaultValue: "Gönderiliyor")
    public static let bookRequestsLoadFailed = localized("bookRequests.loadFailed", defaultValue: "Kitap istekleri yüklenemedi.")
    public static let bookRequestsCreateFailed = localized("bookRequests.createFailed", defaultValue: "Kitap isteği gönderilemedi.")
    public static let bookRequestsVoteFailed = localized("bookRequests.voteFailed", defaultValue: "Oy işlemi tamamlanamadı.")
    public static let bookRequestsActionFailedTitle = localized("bookRequests.actionFailedTitle", defaultValue: "İşlem tamamlanamadı")
    public static let bookRequestsActionFailedMessage = localized("bookRequests.actionFailedMessage", defaultValue: "Lütfen yeniden deneyin.")
    public static let bookRequestsLoginRequiredTitle = localized("bookRequests.loginRequiredTitle", defaultValue: "Giriş gerekli")
    public static let bookRequestsLoginRequiredMessage = localized("bookRequests.loginRequiredMessage", defaultValue: "Kitap isteği göndermek veya oy vermek için giriş yapın.")
    public static let bookRequestsGoToLogin = localized("bookRequests.goToLogin", defaultValue: "Girişe git")

    public static func bookRequestsRequestedBy(_ username: String) -> String {
        String(format: localized("bookRequests.requestedBy", defaultValue: "İsteyen: %@"), username)
    }

    public static func bookRequestsVoteCount(_ count: Int) -> String {
        String(format: localized("bookRequests.voteCount", defaultValue: "%d oy"), count)
    }

    public static func bookRequestsStatus(_ status: String) -> String {
        switch status.uppercased() {
        case "ACQUIRED": localized("bookRequests.status.acquired", defaultValue: "Temin edildi")
        case "REJECTED": localized("bookRequests.status.rejected", defaultValue: "Reddedildi")
        default: localized("bookRequests.status.pending", defaultValue: "Bekliyor")
        }
    }

    public static let conversationsTitle = localized("conversations.title", defaultValue: "Mesajlar")
    public static let conversationsLoading = localized("conversations.loading", defaultValue: "Mesajlar yükleniyor")
    public static let conversationsUnavailableTitle = localized("conversations.unavailableTitle", defaultValue: "Mesajlar alınamadı")
    public static let conversationsEmptyTitle = localized("conversations.emptyTitle", defaultValue: "Henüz mesaj yok")
    public static let conversationsEmptyDescription = localized("conversations.emptyDescription", defaultValue: "Yeni bir özel konuşma başlatabilirsiniz.")
    public static let conversationsLoadFailed = localized("conversations.loadFailed", defaultValue: "Özel mesajlar yüklenemedi.")
    public static let conversationsNew = localized("conversations.new", defaultValue: "Yeni mesaj")
    public static let conversationsMessageTitle = localized("conversations.messageTitle", defaultValue: "Mesaj")
    public static let conversationsReplyPlaceholder = localized("conversations.replyPlaceholder", defaultValue: "Yanıt yazın")
    public static let conversationsRecipient = localized("conversations.recipient", defaultValue: "Alıcı kullanıcı adı")
    public static let conversationsSubject = localized("conversations.subject", defaultValue: "Konu")
    public static let conversationsMessageBody = localized("conversations.messageBody", defaultValue: "Mesaj")
    public static let conversationsSending = localized("conversations.sending", defaultValue: "Gönderiliyor")
    public static let conversationsSendFailedTitle = localized("conversations.sendFailedTitle", defaultValue: "Mesaj gönderilemedi")
    public static let conversationsSendFailed = localized("conversations.sendFailed", defaultValue: "Mesaj gönderilemedi. Alıcıyı ve izinlerinizi kontrol edip yeniden deneyin.")

    public static func conversationsReplyCount(_ count: Int) -> String {
        String(format: localized("conversations.replyCount", defaultValue: "%d yanıt"), count)
    }

    public static let membersTitle = localized("members.title", defaultValue: "Üyeler")
    public static let membersLoading = localized("members.loading", defaultValue: "Üyeler yükleniyor")
    public static let membersUnavailableTitle = localized("members.unavailableTitle", defaultValue: "Üyeler alınamadı")
    public static let membersEmptyTitle = localized("members.emptyTitle", defaultValue: "Üye bulunamadı")
    public static let membersEmptyDescription = localized("members.emptyDescription", defaultValue: "Aramanızı değiştirip yeniden deneyin.")
    public static let membersLoadFailed = localized("members.loadFailed", defaultValue: "Üye dizini yüklenemedi.")
    public static let membersSearchPrompt = localized("members.searchPrompt", defaultValue: "Kullanıcı ara")
    public static let membersTotalLabel = localized("members.totalLabel", defaultValue: "Toplam üye")
    public static let membersSortLabel = localized("members.sortLabel", defaultValue: "Sıralama")
    public static let membersSortAlphabetical = localized("members.sort.alphabetical", defaultValue: "Alfabetik")
    public static let membersSortNewest = localized("members.sort.newest", defaultValue: "En yeni")
    public static let membersSortActive = localized("members.sort.active", defaultValue: "En aktif")
    public static let membersVerified = localized("members.verified", defaultValue: "Doğrulanmış üye")
    public static let membersProfileTitle = localized("members.profileTitle", defaultValue: "Üye Profili")
    public static let membersProfileLoading = localized("members.profileLoading", defaultValue: "Profil yükleniyor")
    public static let membersProfileLoadFailed = localized("members.profileLoadFailed", defaultValue: "Üye profili yüklenemedi.")
    public static let membersStatsSection = localized("members.statsSection", defaultValue: "İstatistikler")
    public static let membersMessagesLabel = localized("members.messagesLabel", defaultValue: "Mesajlar")
    public static let membersReactionsLabel = localized("members.reactionsLabel", defaultValue: "Tepki puanı")
    public static let membersJoinedLabel = localized("members.joinedLabel", defaultValue: "Katılım")
    public static let membersAboutSection = localized("members.aboutSection", defaultValue: "Hakkında")
    public static let membersLocationLabel = localized("members.locationLabel", defaultValue: "Konum")
    public static let membersActionsSection = localized("members.actionsSection", defaultValue: "İşlemler")
    public static let membersFollow = localized("members.follow", defaultValue: "Takip et")
    public static let membersUnfollow = localized("members.unfollow", defaultValue: "Takibi bırak")
    public static let membersBlock = localized("members.block", defaultValue: "Üyeyi engelle")
    public static let membersBlockConfirmation = localized("members.blockConfirmation", defaultValue: "Bu üyeyi engellemek istiyor musunuz?")
    public static let membersBlockCompleted = localized("members.blockCompleted", defaultValue: "Üye engellendi")
    public static let membersActionFailed = localized("members.actionFailed", defaultValue: "Üye işlemi tamamlanamadı.")
    public static let communityDirectorySection = localized("community.directorySection", defaultValue: "Üyeler")

    public static func membersMessageCount(_ count: Int) -> String {
        String(format: localized("members.messageCount", defaultValue: "%d mesaj"), count)
    }

    public static let termsTitle = localized("terms.title", defaultValue: "Topluluk Kuralları")
    public static let termsIntro = localized("terms.intro", defaultValue: "Topluluk alanlarında paylaşım yapmadan önce kullanım şartlarını ve topluluk kurallarını kabul etmelisiniz.")
    public static let termsOpen = localized("terms.open", defaultValue: "Kullanım şartlarını aç")
    public static let termsAcceptToggle = localized("terms.acceptToggle", defaultValue: "Topluluk kurallarını kabul ediyorum")
    public static let termsFooter = localized("terms.footer", defaultValue: "Uygunsuz içerik, taciz, telif ihlali, spam veya kişisel veri paylaşımı kabul edilmez.")
    public static let termsAccept = localized("terms.accept", defaultValue: "Kabul et")
    public static let termsAccepted = localized("terms.accepted", defaultValue: "Topluluk kuralları kabul edildi.")
    public static let termsAcceptFailed = localized("terms.acceptFailed", defaultValue: "Kabul durumu kaydedilemedi.")

    public static let tabHome = localized("tab.home", defaultValue: "Ana Sayfa")
    public static let tabCatalog = localized("tab.catalog", defaultValue: "Kitaplar")
    public static let tabLibrary = localized("tab.library", defaultValue: "Kitaplığım")
    public static let tabCommunity = localized("tab.community", defaultValue: "Topluluk")
    public static let tabAccount = localized("tab.account", defaultValue: "Hesap")

    public static let homeTitle = localized("home.title", defaultValue: "Ekitaplığım")
    public static let homeOpenCatalog = localized("home.openCatalog", defaultValue: "Kitap kataloğunu aç")
    public static let homeContinueReading = localized("home.continueReading", defaultValue: "Kaldığım yerden devam et")
    public static let homeStatsSection = localized("home.stats.section", defaultValue: "Ekitaplığım")
    public static let homeExploreSection = localized("home.explore.section", defaultValue: "Keşfet")
    public static let homeStatsLoading = localized("home.stats.loading", defaultValue: "İstatistikler yükleniyor")
    public static let homeStatsLoadFailed = localized("home.stats.loadFailed", defaultValue: "Site istatistikleri alınamadı.")
    public static let homeBooks = localized("home.stats.books", defaultValue: "E-kitap")
    public static let homeAuthors = localized("home.stats.authors", defaultValue: "Yazar")
    public static let homePublishers = localized("home.stats.publishers", defaultValue: "Yayınevi")
    public static let homeCategories = localized("home.stats.categories", defaultValue: "Kategori")

    public static func homeStatAccessibility(_ label: String, _ value: Int) -> String {
        String(format: localized("home.stats.accessibility", defaultValue: "%@: %d"), label, value)
    }

    public static let loginTitle = localized("login.title", defaultValue: "Giriş")
    public static let loginUsernamePlaceholder = localized("login.usernamePlaceholder", defaultValue: "Kullanıcı adı veya e-posta")
    public static let loginPasswordPlaceholder = localized("login.passwordPlaceholder", defaultValue: "Şifre")
    public static let loginSubmit = localized("login.submit", defaultValue: "Giriş yap")
    public static let loginInvalidCredentials = localized("login.invalidCredentials", defaultValue: "Kullanıcı adı veya şifre doğrulanamadı.")
    public static let loginAppleInvalid = localized("login.appleInvalid", defaultValue: "Apple ile giriş doğrulanamadı.")
    public static let loginAppleFailed = localized("login.appleFailed", defaultValue: "Apple ile giriş tamamlanamadı.")
    public static let loginModePicker = localized("login.modePicker", defaultValue: "Hesap işlemi")
    public static let loginModeLogin = localized("login.mode.login", defaultValue: "Giriş")
    public static let loginModeRegister = localized("login.mode.register", defaultValue: "Kayıt Ol")
    public static let loginRegisterTitle = localized("login.register.title", defaultValue: "Hesap Oluştur")
    public static let loginRegisterSubmit = localized("login.register.submit", defaultValue: "Kayıt ol")
    public static let loginRegisterFailed = localized("login.register.failed", defaultValue: "Kayıt tamamlanamadı. Bilgilerinizi kontrol edip yeniden deneyin.")
    public static let loginEmailPlaceholder = localized("login.emailPlaceholder", defaultValue: "E-posta")
    public static let loginPasswordConfirmation = localized("login.passwordConfirmation", defaultValue: "Şifre tekrar")
    public static let loginPasswordsMismatch = localized("login.passwordsMismatch", defaultValue: "Şifreler eşleşmiyor.")
    public static let loginAcceptLegal = localized("login.acceptLegal", defaultValue: "Kullanım şartlarını ve gizlilik politikasını kabul ediyorum")
    public static let loginForgotPassword = localized("login.forgotPassword", defaultValue: "Şifremi unuttum")
    public static let loginResetTitle = localized("login.reset.title", defaultValue: "Şifre Sıfırlama")
    public static let loginResetSubmit = localized("login.reset.submit", defaultValue: "Sıfırlama bağlantısı gönder")
    public static let loginResetSubmitted = localized("login.reset.submitted", defaultValue: "Bu e-posta kayıtlıysa sıfırlama bağlantısı gönderildi.")
    public static let loginResetFailed = localized("login.reset.failed", defaultValue: "Şifre sıfırlama isteği gönderilemedi.")
    public static let loginResetPrivacyNotice = localized("login.reset.privacyNotice", defaultValue: "Güvenlik nedeniyle e-posta adresinin kayıtlı olup olmadığı açıklanmaz.")
    public static let loginBackToLogin = localized("login.backToLogin", defaultValue: "Giriş ekranına dön")

    public static let settingsTitle = localized("settings.title", defaultValue: "Hesap")
    public static let settingsUser = localized("settings.user", defaultValue: "Kullanıcı")
    public static let settingsSigningIn = localized("settings.signingIn", defaultValue: "Giriş yapılıyor")
    public static let settingsSignOut = localized("settings.signOut", defaultValue: "Çıkış yap")
    public static let settingsSignIn = localized("settings.signIn", defaultValue: "Giriş yap")
    public static let settingsProfileSection = localized("settings.profileSection", defaultValue: "Profil")
    public static let settingsProfile = localized("settings.profile", defaultValue: "Profilim")
    public static let settingsNotifications = localized("settings.notifications", defaultValue: "Bildirimler")
    public static let settingsAccountSection = localized("settings.accountSection", defaultValue: "Hesap")
    public static let settingsStartAccountDeletion = localized("settings.startAccountDeletion", defaultValue: "Hesap silme talebi başlat")
    public static let settingsLegalSection = localized("settings.legalSection", defaultValue: "Yasal")
    public static let settingsPrivacyPolicy = localized("settings.privacyPolicy", defaultValue: "Gizlilik Politikası")
    public static let settingsTerms = localized("settings.terms", defaultValue: "Kullanım Şartları")
    public static let settingsSupport = localized("settings.support", defaultValue: "Destek ve İletişim")
    public static let settingsPrivacySection = localized("settings.privacySection", defaultValue: "Gizlilik")
    public static let settingsPrivacyPreferences = localized("settings.privacyPreferences", defaultValue: "Gizlilik tercihleri")

    public static let premiumTitle = localized("premium.title", defaultValue: "Ekitaplığım Premium")
    public static let premiumDescription = localized("premium.description", defaultValue: "Premium üyelik, sunucu tarafından belirlenen daha yüksek veya sınırsız okuma ve indirme hakları sağlar.")
    public static let premiumPlans = localized("premium.plans", defaultValue: "Abonelik Planları")
    public static let premiumLoading = localized("premium.loading", defaultValue: "Apple ürünleri yükleniyor")
    public static let premiumPurchasing = localized("premium.purchasing", defaultValue: "Satın alma doğrulanıyor")
    public static let premiumPurchased = localized("premium.purchased", defaultValue: "Premium üyeliğiniz etkinleştirildi.")
    public static let premiumRestored = localized("premium.restored", defaultValue: "Satın almanız geri yüklendi ve doğrulandı.")
    public static let premiumPending = localized("premium.pending", defaultValue: "Satın alma Apple onayı bekliyor.")
    public static let premiumRestore = localized("premium.restore", defaultValue: "Satın almaları geri yükle")
    public static let premiumManageSubscriptions = localized("premium.manageSubscriptions", defaultValue: "Apple aboneliklerini yönet")
    public static let premiumLoginRequired = localized("premium.loginRequired", defaultValue: "Satın alma için Ekitaplığım hesabınıza giriş yapın.")
    public static let premiumRenewalDisclosure = localized("premium.renewalDisclosure", defaultValue: "Ödeme Apple ID hesabınızdan alınır. Abonelik, geçerli dönemin bitiminden en az 24 saat önce iptal edilmezse otomatik yenilenir. Fiyat ve dönem Apple satın alma ekranında gösterilir; aboneliği App Store hesap ayarlarından yönetebilir veya iptal edebilirsiniz.")
    public static let premiumProductsFailed = localized("premium.error.products", defaultValue: "Apple ürün bilgileri alınamadı.")
    public static let premiumProductMissing = localized("premium.error.productMissing", defaultValue: "Seçilen abonelik Apple mağazasında bulunamadı.")
    public static let premiumPurchaseFailed = localized("premium.error.purchase", defaultValue: "Satın alma tamamlanamadı.")
    public static let premiumVerificationFailed = localized("premium.error.verification", defaultValue: "Satın alma güvenli biçimde doğrulanamadı.")
    public static let premiumNothingToRestore = localized("premium.error.nothingToRestore", defaultValue: "Geri yüklenecek etkin bir premium abonelik bulunamadı.")
    public static let premiumRestoreFailed = localized("premium.error.restore", defaultValue: "Satın almalar geri yüklenemedi veya sunucuda doğrulanamadı.")

    public static let catalogTitle = localized("catalog.title", defaultValue: "Kitaplar")
    public static let catalogLoading = localized("catalog.loading", defaultValue: "Kitaplar yükleniyor")
    public static let catalogUnavailableTitle = localized("catalog.unavailableTitle", defaultValue: "Katalog açılamadı")
    public static let catalogEmptyTitle = localized("catalog.emptyTitle", defaultValue: "Kitap bulunamadı")
    public static let catalogEmptyDescription = localized("catalog.emptyDescription", defaultValue: "Aramanızı değiştirip tekrar deneyin.")
    public static let catalogSearchPrompt = localized("catalog.searchPrompt", defaultValue: "Kitap, yazar veya ISBN")
    public static let catalogLoadFailed = localized("catalog.loadFailed", defaultValue: "Kitaplar alınamadı. Bağlantınızı kontrol edip tekrar deneyin.")
    public static let catalogFiltersTitle = localized("catalog.filters.title", defaultValue: "Filtreler")
    public static let catalogFilterDetails = localized("catalog.filters.details", defaultValue: "Kitap Bilgileri")
    public static let catalogFilterAuthor = localized("catalog.filters.author", defaultValue: "Yazar")
    public static let catalogFilterPublisher = localized("catalog.filters.publisher", defaultValue: "Yayınevi")
    public static let catalogFilterISBN = localized("catalog.filters.isbn", defaultValue: "ISBN")
    public static let catalogFilterPremium = localized("catalog.filters.premium", defaultValue: "Yalnızca premium kitaplar")
    public static let catalogFilterCategory = localized("catalog.filters.category", defaultValue: "Kategori")
    public static let catalogFilterAllCategories = localized("catalog.filters.allCategories", defaultValue: "Tüm kategoriler")
    public static let catalogFilterOrder = localized("catalog.filters.order", defaultValue: "Sıralama")
    public static let catalogOrderLatest = localized("catalog.order.latest", defaultValue: "En yeni")
    public static let catalogOrderPopular = localized("catalog.order.popular", defaultValue: "Popüler")
    public static let catalogOrderRated = localized("catalog.order.rated", defaultValue: "Puan")
    public static let catalogFilterReset = localized("catalog.filters.reset", defaultValue: "Sıfırla")
    public static let catalogFilterApply = localized("catalog.filters.apply", defaultValue: "Uygula")
    public static let catalogLoadMore = localized("catalog.loadMore", defaultValue: "Daha fazla yükle")
    public static let catalogLoadingMore = localized("catalog.loadingMore", defaultValue: "Yükleniyor")
    public static let catalogShowGrid = localized("catalog.display.grid", defaultValue: "Izgara görünümüne geç")
    public static let catalogShowList = localized("catalog.display.list", defaultValue: "Liste görünümüne geç")

    public static let libraryTitle = localized("library.title", defaultValue: "Kitaplığım")
    public static let libraryLoading = localized("library.loading", defaultValue: "Kitaplık yükleniyor")
    public static let libraryUnavailableTitle = localized("library.unavailableTitle", defaultValue: "Kitaplık alınamadı")
    public static let libraryEmptyTitle = localized("library.emptyTitle", defaultValue: "Kitap bulunamadı")
    public static let libraryEmptyDescription = localized("library.emptyDescription", defaultValue: "Bu rafta henüz kitap yok.")
    public static let libraryLoadFailed = localized("library.loadFailed", defaultValue: "Kitaplık bilgileri alınamadı.")
    public static let libraryDownloadsLabel = localized("library.downloadsLabel", defaultValue: "İndirilenler")
    public static let libraryShelfPicker = localized("library.shelfPicker", defaultValue: "Raf")
    public static let libraryShelfAll = localized("library.shelf.all", defaultValue: "Tümü")
    public static let libraryShelfReading = localized("library.shelf.reading", defaultValue: "Okuyorum")
    public static let libraryShelfFinished = localized("library.shelf.finished", defaultValue: "Okudum")
    public static let libraryShelfFavorites = localized("library.shelf.favorites", defaultValue: "Favoriler")
    public static let libraryShelfDownloads = localized("library.shelf.downloads", defaultValue: "İndirilen")
    public static let libraryReadingProgressLabel = localized("library.readingProgressLabel", defaultValue: "Okuma ilerlemesi")
    public static let libraryFavoriteBadge = localized("library.favoriteBadge", defaultValue: "Favori")
    public static let libraryDownloadedBadge = localized("library.downloadedBadge", defaultValue: "İndirildi")

    public static let downloadsTitle = localized("downloads.title", defaultValue: "İndirilenler")
    public static let downloadsEmptyTitle = localized("downloads.emptyTitle", defaultValue: "İndirilen kitap yok")
    public static let downloadsEmptyDescription = localized("downloads.emptyDescription", defaultValue: "Çevrimdışı indirdiğiniz kitaplar burada görünür.")
    public static let downloadsNotDownloaded = localized("downloads.notDownloaded", defaultValue: "İndirilmedi")
    public static let downloadsQueued = localized("downloads.queued", defaultValue: "Sırada")

    public static func commonBookNumber(_ bookID: String) -> String {
        String(format: localized("common.bookNumber", defaultValue: "Kitap #%@"), bookID)
    }

    public static func commonPercent(_ percent: Int) -> String {
        String(format: localized("common.percent", defaultValue: "%%%d"), percent)
    }

    public static func downloadsDownloading(_ percent: Int) -> String {
        String(format: localized("downloads.downloading", defaultValue: "İndiriliyor %d%%"), percent)
    }

    public static func downloadsReady(_ fileName: String) -> String {
        String(format: localized("downloads.ready", defaultValue: "Hazır: %@"), fileName)
    }

    public static let communityTitle = localized("community.title", defaultValue: "Topluluk")
    public static let communityLoading = localized("community.loading", defaultValue: "Forumlar yükleniyor")
    public static let communityUnavailableTitle = localized("community.unavailableTitle", defaultValue: "Forumlar alınamadı")
    public static let communityForumsSection = localized("community.forumsSection", defaultValue: "Forumlar")
    public static let communitySafetySection = localized("community.safetySection", defaultValue: "Güvenlik")
    public static let communityBlockUser = localized("community.blockUser", defaultValue: "Kullanıcı engelle")
    public static let communityBlockedUsers = localized("community.blockedUsers", defaultValue: "Engellenen kullanıcılar")
    public static let communityForumsLoadFailed = localized("community.forumsLoadFailed", defaultValue: "Forum listesi alınamadı.")

    public static let blockMemberTitle = localized("blockMember.title", defaultValue: "Kullanıcı engelle")
    public static let blockMemberUserIdPlaceholder = localized("blockMember.userIdPlaceholder", defaultValue: "Kullanıcı ID")
    public static let blockMemberFooter = localized("blockMember.footer", defaultValue: "Engellenen kullanıcının içerikleri uygun ekranlarda gizlenir. Kötüye kullanım durumunda ayrıca içerik raporu gönderin.")
    public static let blockMemberSubmit = localized("blockMember.submit", defaultValue: "Kullanıcıyı engelle")
    public static let blockMemberSuccess = localized("blockMember.success", defaultValue: "Kullanıcı engellendi.")
    public static let blockMemberFailure = localized("blockMember.failure", defaultValue: "Kullanıcı engellenemedi.")

    public static let blockedMembersTitle = localized("blockedMembers.title", defaultValue: "Engellenenler")
    public static let blockedMembersLoading = localized("blockedMembers.loading", defaultValue: "Engellenenler yükleniyor")
    public static let blockedMembersUnavailableTitle = localized("blockedMembers.unavailableTitle", defaultValue: "Liste alınamadı")
    public static let blockedMembersEmptyTitle = localized("blockedMembers.emptyTitle", defaultValue: "Engellenen kullanıcı yok")
    public static let blockedMembersRemove = localized("blockedMembers.remove", defaultValue: "Kaldır")
    public static let blockedMembersLoadFailed = localized("blockedMembers.loadFailed", defaultValue: "Engellenen kullanıcılar alınamadı.")

    public static let forumThreadsLoading = localized("forumThreads.loading", defaultValue: "Konular yükleniyor")
    public static let forumThreadsUnavailableTitle = localized("forumThreads.unavailableTitle", defaultValue: "Konular alınamadı")
    public static let forumThreadsEmptyTitle = localized("forumThreads.emptyTitle", defaultValue: "Konu yok")
    public static let forumThreadsInvalidForum = localized("forumThreads.invalidForum", defaultValue: "Forum kimliği geçersiz.")
    public static let forumThreadsLoadFailed = localized("forumThreads.loadFailed", defaultValue: "Forum konuları alınamadı.")

    public static func forumThreadsMeta(username: String, replyCount: Int, viewCount: Int) -> String {
        String(format: localized("forumThreads.meta", defaultValue: "%@ • %d cevap • %d görüntüleme"), username, replyCount, viewCount)
    }

    public static let forumThreadLoading = localized("forumThread.loading", defaultValue: "Mesajlar yükleniyor")
    public static let forumThreadReportPost = localized("forumThread.reportPost", defaultValue: "Mesajı bildir")
    public static let forumThreadBlockUser = localized("forumThread.blockUser", defaultValue: "Kullanıcıyı engelle")
    public static let forumThreadReplySection = localized("forumThread.replySection", defaultValue: "Cevap yaz")
    public static let forumThreadReplyTextLabel = localized("forumThread.replyTextLabel", defaultValue: "Cevap metni")
    public static let forumThreadSubmitReply = localized("forumThread.submitReply", defaultValue: "Cevabı gönder")
    public static let forumThreadInvalidThread = localized("forumThread.invalidThread", defaultValue: "Konu kimliği geçersiz.")
    public static let forumThreadLoadFailed = localized("forumThread.loadFailed", defaultValue: "Konu mesajları alınamadı.")
    public static let forumThreadReplyPublished = localized("forumThread.replyPublished", defaultValue: "Cevabınız yayınlandı.")
    public static let forumThreadReplyFailed = localized("forumThread.replyFailed", defaultValue: "Cevap gönderilemedi.")

    public static let notificationsTitle = localized("notifications.title", defaultValue: "Bildirimler")
    public static let notificationsLoading = localized("notifications.loading", defaultValue: "Bildirimler yükleniyor")
    public static let notificationsUnavailableTitle = localized("notifications.unavailableTitle", defaultValue: "Bildirimler alınamadı")
    public static let notificationsEmptyTitle = localized("notifications.emptyTitle", defaultValue: "Bildirim yok")
    public static let notificationsUnread = localized("notifications.unread", defaultValue: "Okunmamış")
    public static let notificationsNew = localized("notifications.new", defaultValue: "Yeni")
    public static let notificationsMarkAllRead = localized("notifications.markAllRead", defaultValue: "Tümünü oku")
    public static let notificationsLoadFailed = localized("notifications.loadFailed", defaultValue: "Bildirimler alınamadı.")

    public static let profileTitle = localized("profile.title", defaultValue: "Profilim")
    public static let profileLoading = localized("profile.loading", defaultValue: "Profil yükleniyor")
    public static let profileUnavailableTitle = localized("profile.unavailableTitle", defaultValue: "Profil alınamadı")
    public static let profileEmptyTitle = localized("profile.emptyTitle", defaultValue: "Profil yok")
    public static let profileStatsSection = localized("profile.statsSection", defaultValue: "İstatistikler")
    public static let profileMessageCount = localized("profile.messageCount", defaultValue: "Mesaj")
    public static let profileReactionScore = localized("profile.reactionScore", defaultValue: "Tepki")
    public static let profileRegisterDate = localized("profile.registerDate", defaultValue: "Kayıt tarihi")
    public static let profilePermissionsSection = localized("profile.permissionsSection", defaultValue: "Yetki")
    public static let profileStaff = localized("profile.staff", defaultValue: "Personel")
    public static let profileCanEdit = localized("profile.canEdit", defaultValue: "Düzenleme")
    public static let profileYes = localized("profile.yes", defaultValue: "Evet")
    public static let profileNo = localized("profile.no", defaultValue: "Hayır")
    public static let profileOpen = localized("profile.open", defaultValue: "Açık")
    public static let profileClosed = localized("profile.closed", defaultValue: "Kapalı")
    public static let profileLoadFailed = localized("profile.loadFailed", defaultValue: "Profil bilgileri alınamadı.")
    public static let profileEditTitle = localized("profile.edit.title", defaultValue: "Profili Düzenle")
    public static let profileEditGeneralSection = localized("profile.edit.generalSection", defaultValue: "Genel Bilgiler")
    public static let profileEditAbout = localized("profile.edit.about", defaultValue: "Hakkında")
    public static let profileEditLocation = localized("profile.edit.location", defaultValue: "Konum")
    public static let profileEditWebsite = localized("profile.edit.website", defaultValue: "Web sitesi")
    public static let profileEditActivityVisible = localized("profile.edit.activityVisible", defaultValue: "Çevrimiçi durumumu göster")
    public static let profileEditSave = localized("profile.edit.save", defaultValue: "Kaydet")
    public static let profileEditSaving = localized("profile.edit.saving", defaultValue: "Kaydediliyor")
    public static let profileEditSaveFailed = localized("profile.edit.saveFailed", defaultValue: "Profil değişiklikleri kaydedilemedi.")

    private static func localized(_ key: String.LocalizationValue, defaultValue: String.LocalizationValue) -> String {
        String(localized: key, defaultValue: defaultValue, bundle: .module)
    }
}
